---
title: Saari
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: projects
  values:
    image: 
    description: 
    lead: 
    is-featured: 
    is-hero: 
    layout: project
    services:
    - 
    feature-image: 
    images: 
    details:
    - title: 
      text: 
    testimonial:
      text: 
      cite: 
- scope:
    path: ''
    type: pages
  values:
    description: 
url: https://www.saari.co.uk
description: London-based digital strategy, marketing, brand and business development
  consultancy, delivering increased market awareness and growth for our clients.
permalink: pretty
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: http://garethjohnsdesign.com
company: Saari Ltd
email: info@saari.co.uk
phone-number: "+44(0)14 9128 2232"
google_site_verification: u9wxNSHXWxQGvkFjTWDtL6xo1LcSm7GRj0yODZRHSQA
analytics: UA-116993730-1
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%d %B %Y"
future: true
social:
  facebook: https://www.facebook.com/SaariLtd/
  instagram: https://www.instagram.com/saariltd/
  linkedin: https://uk.linkedin.com/company/saari-ltd-
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
