field: 177d26d8-196e-40fa-80c8-8dc29f7a4139
fieldLayouts:
  a9e89010-21d7-40cd-816d-10a4b04aa6d6:
    tabs:
      -
        fields:
          3bdf54ec-e1d3-4c6b-b951-30ec74d1ee0c:
            required: true
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  3bdf54ec-e1d3-4c6b-b951-30ec74d1ee0c:
    contentColumnType: string(255)
    fieldGroup: null
    handle: socialLink
    instructions: ''
    name: Link
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: linkedin
name: LinkedIn
sortOrder: 4
