fieldLayouts:
  7823a58c-7697-4071-bc3e-3c95a56435a2:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 04ab3c60-f325-48ea-bf96-347befb870e0
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 19816479-1914-4bba-a067-c588dfde9af9
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: a217b31b-0447-45c7-b27f-2a37ed6bf1cf
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Contact
        sortOrder: 1
      -
        elements:
          -
            fieldUid: dfb201c1-5d86-40c2-8ef8-8a447a607828
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fe83906d-6f96-4f77-9151-41326628a78d
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1abe3543-0a12-4298-ad7d-1a93ca2d280c
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: contact
hasTitleField: false
name: Contact
section: 90f9271a-e759-4cb5-b190-63a383235d11 # Contact
sortOrder: 1
titleFormat: '{section.name|raw}'
