fieldLayouts:
  5513241e-2d84-4bf1-ab30-780233b08335:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: a217b31b-0447-45c7-b27f-2a37ed6bf1cf
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 9077aec3-15f3-4b0d-bd7c-cce9aa875cdc
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Profile
        sortOrder: 1
      -
        elements:
          -
            fieldUid: dfb201c1-5d86-40c2-8ef8-8a447a607828
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fe83906d-6f96-4f77-9151-41326628a78d
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1abe3543-0a12-4298-ad7d-1a93ca2d280c
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: profile
hasTitleField: false
name: Profile
section: de5b0e74-9873-49f7-b384-1dad088ea164 # Profile
sortOrder: 1
titleFormat: '{section.name|raw}'
