fieldLayouts:
  1681f746-e5e6-4770-a65f-0d76dfb9c745:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: cc7a7777-17c5-45ef-829d-9b277cb85134
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Projects
        sortOrder: 1
      -
        elements:
          -
            fieldUid: dfb201c1-5d86-40c2-8ef8-8a447a607828
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fe83906d-6f96-4f77-9151-41326628a78d
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1abe3543-0a12-4298-ad7d-1a93ca2d280c
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: projects
hasTitleField: false
name: Projects
section: 55d9d512-7f65-4622-9249-4b060f040a05 # Projects
sortOrder: 1
titleFormat: '{section.name|raw}'
