contentColumnType: string
fieldGroup: dfe9b0d4-736b-4fbd-a584-88932d8d56a9
handle: clients
instructions: ''
name: Clients
searchable: true
settings:
  contentTable: '{{%matrixcontent_clients}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
