contentColumnType: string
fieldGroup: b37424aa-eff2-4e8b-825c-20c18bb4148f
handle: heroImage
instructions: 'This is not required but will replace the standard image on the homepage banner and header of project page if used.'
name: 'Hero Image'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:244f7440-a428-4998-8c23-00991784b369'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add a feature image'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:244f7440-a428-4998-8c23-00991784b369'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
