contentColumnType: string
fieldGroup: dfe9b0d4-736b-4fbd-a584-88932d8d56a9
handle: projects
instructions: ''
name: Projects
searchable: false
settings:
  limit: '6'
  localizeRelations: false
  selectionLabel: 'Add a project'
  source: null
  sources:
    - 'section:32174234-e8c3-40d4-9725-77ff2bd2366a' # Primary Projects
  targetSiteId: null
  validateRelatedElements: ''
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
