contentColumnType: text
fieldGroup: ce97b294-fcb7-4d2e-beaf-0027be256fd1
handle: seoTitle
instructions: ''
name: 'SEO Title'
searchable: true
settings:
  byteLimit: null
  charLimit: 60
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
