enableVersioning: true
handle: music
name: Music
propagationMethod: all
siteSettings:
  8a2043ba-0ab6-482c-bb78-9c06b90e1891: # Saari
    enabledByDefault: true
    hasUrls: true
    template: music/music
    uriFormat: music
type: single
