enableVersioning: true
handle: musicProjects
name: 'Music Projects'
propagationMethod: all
siteSettings:
  8a2043ba-0ab6-482c-bb78-9c06b90e1891: # Saari
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: ''
structure:
  maxLevels: 1
  uid: 3ec2a683-4fb0-45c6-bd9a-8cac46b40048
type: structure
