enableVersioning: true
handle: profile
name: Profile
propagationMethod: all
siteSettings:
  8a2043ba-0ab6-482c-bb78-9c06b90e1891: # Saari
    enabledByDefault: true
    hasUrls: true
    template: profile/profile
    uriFormat: profile
type: single
